# Generated by Django 3.0.4 on 2020-03-26 04:22

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import ingest.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=255, null=True, unique=True, verbose_name='Nombre')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InfectionSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=255, null=True, unique=True, verbose_name='Nombre')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('patient_raw_file_id', models.IntegerField(unique=True, verbose_name='ID de archivo')),
                ('gender', models.CharField(max_length=255, verbose_name='género')),
                ('nationality', models.CharField(max_length=255, verbose_name='nacionalidad')),
                ('address', models.CharField(max_length=255, verbose_name='dirección')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='notas')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Nombre')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TravelFrom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=255, null=True, unique=True, verbose_name='Nombre')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RawFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('file', models.FileField(upload_to=ingest.models._raw_file_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['csv', 'xlsx'])], verbose_name='archivo')),
                ('notes', models.TextField(blank=True, verbose_name='notas')),
                ('confirmed', models.BooleanField(default=False, verbose_name='confirmado')),
                ('is_parsed', models.BooleanField(default=False, verbose_name='Parseado')),
                ('_iew', models.TextField(db_column='Info, errors and Warnings', default='null')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_files', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('idx_raw_file', models.IntegerField(verbose_name='Indice en archivo')),
                ('event_raw_file_id', models.IntegerField(unique=True, verbose_name='Id en archivo')),
                ('status', models.CharField(choices=[('suspected', 'Sospechoso'), ('active', 'Activo'), ('recovered', 'Recuperado'), ('deceased', 'Fallecido')], max_length=50)),
                ('lock_address', models.CharField(max_length=255)),
                ('has_symptom', models.BooleanField(null=True)),
                ('first_simptoms_date', models.DateField(null=True)),
                ('confirmed_date', models.DateField(null=True)),
                ('deceased_date', models.DateField(null=True)),
                ('discharge_date', models.DateField(null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='ingest.Patient', verbose_name='Paciente')),
                ('raw_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='ingest.RawFile', verbose_name='Archivo')),
                ('symptom', models.ManyToManyField(related_name='events', to='ingest.Symptom')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
