# Generated by Django 3.0.4 on 2020-04-15 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawfile',
            name='size',
            field=models.IntegerField(null=True),
        ),
    ]
