# Generated by Django 3.0.4 on 2020-04-16 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clasificacionepidemiologica',
            old_name='modifed_by',
            new_name='modified_by',
        ),
        migrations.RenameField(
            model_name='departamento',
            old_name='modifed_by',
            new_name='modified_by',
        ),
        migrations.RenameField(
            model_name='evento',
            old_name='modifed_by',
            new_name='modified_by',
        ),
        migrations.RenameField(
            model_name='localidad',
            old_name='modifed_by',
            new_name='modified_by',
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='modifed_by',
            new_name='modified_by',
        ),
        migrations.RenameField(
            model_name='pais',
            old_name='modifed_by',
            new_name='modified_by',
        ),
        migrations.RenameField(
            model_name='provincia',
            old_name='modifed_by',
            new_name='modified_by',
        ),
        migrations.RenameField(
            model_name='sintoma',
            old_name='modifed_by',
            new_name='modified_by',
        ),
        migrations.RenameField(
            model_name='tipoevento',
            old_name='modifed_by',
            new_name='modified_by',
        ),
    ]
