# Generated by Django 3.0.4 on 2020-04-14 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clasificacionepidemiologica',
            old_name='nombre',
            new_name='nombre_ce',
        ),
        migrations.RenameField(
            model_name='departamento',
            old_name='nombre',
            new_name='nombre_departamento',
        ),
        migrations.RenameField(
            model_name='determinacionresultado',
            old_name='nombre',
            new_name='nombre_dr',
        ),
        migrations.RenameField(
            model_name='determinacionresultado',
            old_name='notas',
            new_name='notas_dr',
        ),
        migrations.RenameField(
            model_name='evento',
            old_name='notas',
            new_name='notas_evento',
        ),
        migrations.RenameField(
            model_name='financiamiento',
            old_name='nombre',
            new_name='nombre_fin',
        ),
        migrations.RenameField(
            model_name='localidad',
            old_name='nombre',
            new_name='nombre_localidad',
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='nombre',
            new_name='nombre_paciente',
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='notas',
            new_name='notas_paciente',
        ),
        migrations.RenameField(
            model_name='pais',
            old_name='nombre',
            new_name='nombre_pais',
        ),
        migrations.RenameField(
            model_name='provincia',
            old_name='nombre',
            new_name='nombre_provincia',
        ),
        migrations.RenameField(
            model_name='sintoma',
            old_name='nombre',
            new_name='nombre_sintoma',
        ),
        migrations.RenameField(
            model_name='sintoma',
            old_name='notas',
            new_name='notas_sintoma',
        ),
        migrations.RenameField(
            model_name='tipoevento',
            old_name='nombre',
            new_name='nombre_tipo_evento',
        ),
        migrations.RenameField(
            model_name='tipoevento',
            old_name='notas',
            new_name='notas_tipo_evento',
        ),
    ]
