# Generated by Django 3.0.4 on 2020-03-20 23:55

import django.core.validators
from django.db import migrations, models
import ingest.models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawfile',
            name='confirmed',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='rawfile',
            name='file',
            field=models.FileField(upload_to=ingest.models._raw_file_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['csv', 'xlsx'])]),
        ),
        migrations.AlterField(
            model_name='rawfile',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
