# Generated by Django 3.0.4 on 2020-03-22 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0002_auto_20200320_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawfile',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
