# Generated by Django 3.0.4 on 2020-04-15 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0002_evento_id_evento'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='color_de_pero',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
