# Generated by Django 3.0.4 on 2020-04-13 05:54

import django.core.validators
from django.db import migrations, models
import ingest.models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0002_auto_20200413_0533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawfile',
            name='file',
            field=models.FileField(upload_to=ingest.models._raw_file_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['csv', 'xlsx'])], verbose_name='archivo'),
        ),
    ]
