# Generated by Django 3.0.4 on 2020-04-17 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0002_auto_20200416_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawfile',
            name='broken',
            field=models.BooleanField(default=False, verbose_name='Roto'),
        ),
    ]
