# Generated by Django 3.0.4 on 2020-04-15 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0003_paciente_color_de_pero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='color_de_pero',
        ),
    ]
