# Generated by Django 3.0.4 on 2020-03-25 04:26

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import ingest.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ingest', '0003_auto_20200322_2030'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfectionSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('desc', models.CharField(max_length=255, verbose_name='Description')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('patient_raw_file_id', models.IntegerField(unique=True, verbose_name='ID de archivo')),
                ('gender', models.CharField(max_length=255, verbose_name='género')),
                ('nationality', models.CharField(max_length=255, verbose_name='nacionalidad')),
                ('address', models.CharField(max_length=255, verbose_name='dirección')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='notas')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sintoms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('description', models.CharField(max_length=255, verbose_name='description')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='rawfile',
            name='confirmed',
            field=models.BooleanField(default=False, verbose_name='confirmado'),
        ),
        migrations.AlterField(
            model_name='rawfile',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_files', to=settings.AUTH_USER_MODEL, verbose_name='creado por'),
        ),
        migrations.AlterField(
            model_name='rawfile',
            name='file',
            field=models.FileField(upload_to=ingest.models._raw_file_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['csv', 'xlsx'])], verbose_name='archivo'),
        ),
        migrations.AlterField(
            model_name='rawfile',
            name='notes',
            field=models.TextField(blank=True, verbose_name='notas'),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('event_raw_file_id', models.IntegerField(unique=True)),
                ('status', models.CharField(choices=[('suspected', 'Sospechoso'), ('active', 'Activo'), ('recovered', 'Recuperado'), ('deceased', 'Fallecido')], max_length=50)),
                ('lock_address', models.CharField(max_length=255)),
                ('has_simptoms', models.BooleanField(null=True)),
                ('first_simptoms_date', models.DateField(null=True)),
                ('confirmed_date', models.DateField(null=True)),
                ('deceased_date', models.DateField(null=True)),
                ('discharge_date', models.DateField(null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='ingest.Patient', verbose_name='Paciente')),
                ('raw_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='ingest.RawFile', verbose_name='Archivo')),
                ('sintoms', models.ManyToManyField(related_name='events', to='ingest.Sintoms')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
