# Generated by Django 3.0.4 on 2020-03-26 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0004_auto_20200326_0442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rawfile',
            name='_iew',
        ),
    ]
