# Generated by Django 3.0.4 on 2020-04-21 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0005_auto_20200419_2205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='id_evento',
        ),
        migrations.RemoveField(
            model_name='eventosignosintoma',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='eventosignosintoma',
            name='modified_by',
        ),
    ]
