# Generated by Django 3.0.4 on 2020-03-26 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0005_remove_rawfile__iew'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.PositiveIntegerField(null=True, verbose_name='edad'),
        ),
    ]
