# Generated by Django 3.0.4 on 2020-04-27 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0006_auto_20200421_0124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventosignosintoma',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingest.Evento'),
        ),
    ]
