# Generated by Django 3.0.4 on 2020-04-27 20:50

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0007_auto_20200427_1845'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='clasificacionepidemiologica',
            managers=[
                ('plots', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='departamento',
            managers=[
                ('plots', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='evento',
            managers=[
                ('plots', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='localidad',
            managers=[
                ('plots', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='paciente',
            managers=[
                ('plots', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='pais',
            managers=[
                ('plots', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='provincia',
            managers=[
                ('plots', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='sintoma',
            managers=[
                ('plots', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='tipoevento',
            managers=[
                ('plots', django.db.models.manager.Manager()),
            ],
        ),
    ]
