# Generated by Django 3.0.4 on 2020-04-27 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0008_auto_20200427_2050'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='clasificacionepidemiologica',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='departamento',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='evento',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='localidad',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='paciente',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='pais',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='provincia',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='sintoma',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='tipoevento',
            managers=[
            ],
        ),
    ]
