# Generated by Django 3.0.4 on 2020-04-29 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReportConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.TextField(default='\n<p>Generated with Brooks <code>{{now.isoformat()}}</code></p>\n<hr>\n', verbose_name='encabezado')),
                ('body', models.TextField(default='\n<h1>Informe diario {{now.strftime(\'%Y-%m-%d\')}}</h1>\n\n{% for m in models %}\n<div id="model-{{m.model_name()}}">\n    <h2>{{ m.model_name() }}</h2>\n\n    <p><q>{{ m.model_resume() }}</q></p>\n\n    {% for plot in m.plots.plot_all() %}\n        {{ plot.to_html() }}\n    {% endfor %}\n    </div>\n{% endfor %}\n', verbose_name='Cuerpo')),
                ('footer', models.TextField(default='\n<hr>\n<p>Generated with Brooks <code>{{now.isoformat()}}</code></p>\n<p><a href="http://ivco19.github.io/">http://ivco19.github.io/</a></p>\n', verbose_name='pie')),
            ],
            options={
                'verbose_name': 'Configuración de reporte',
            },
        ),
    ]
