# Generated by Django 3.0.4 on 2020-03-22 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReportConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.TextField(default='Generated with brooks')),
                ('footer', models.TextField(default='Generated at {{now}}')),
            ],
            options={
                'verbose_name': 'Site Configuration',
            },
        ),
    ]
