# Generated by Django 3.0.4 on 2020-03-25 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reportconfiguration',
            options={'verbose_name': 'Configuración de reporte'},
        ),
        migrations.AlterField(
            model_name='reportconfiguration',
            name='footer',
            field=models.TextField(default='Generated at {{now}}', verbose_name='pie'),
        ),
        migrations.AlterField(
            model_name='reportconfiguration',
            name='header',
            field=models.TextField(default='Generated with brooks', verbose_name='encabezado'),
        ),
    ]
