# Generated by Django 3.0.4 on 2020-04-27 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0002_auto_20200325_0426'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportconfiguration',
            name='body',
            field=models.TextField(default='Generated at {{now}}', verbose_name='Cuerpo'),
        ),
    ]
