# Generated by Django 3.0.4 on 2020-04-27 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0005_auto_20200427_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportconfiguration',
            name='footer',
            field=models.TextField(default='\n<hr>\n<p>Generated with Brooks <code>{{now|date:\'Y-m-d H:i\'}}</code></p>\n<p><a href="http://ivco19.github.io/">http://ivco19.github.io/</a></p>\n', verbose_name='pie'),
        ),
        migrations.AlterField(
            model_name='reportconfiguration',
            name='header',
            field=models.TextField(default="<p>Generated with Brooks <code>{{now|date:'Y-m-d H:i'}}</code></p>", verbose_name='encabezado'),
        ),
    ]
