# Generated by Django 3.0.4 on 2020-04-28 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0006_auto_20200427_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportconfiguration',
            name='body',
            field=models.TextField(default='\n<h1>Informe diario {{now.strftime(\'%Y-%m-%d\')}}</h1>\n\n{% for m in models %}\n<div id="model-{{m.model_name()}}">\n<h2>{{ m.model_name() }}</h2>\n{% for plot in m.plots.plot_all() %}\n{{ plot.to_html() }}\n{% endfor %}\n\n</div>\n{% endfor %}\n', verbose_name='Cuerpo'),
        ),
        migrations.AlterField(
            model_name='reportconfiguration',
            name='footer',
            field=models.TextField(default='\n<hr>\n<p>Generated with Brooks <code>{{now.isoformat()}}</code></p>\n<p><a href="http://ivco19.github.io/">http://ivco19.github.io/</a></p>\n', verbose_name='pie'),
        ),
        migrations.AlterField(
            model_name='reportconfiguration',
            name='header',
            field=models.TextField(default='\n<p>Generated with Brooks <code>{{now.isoformat()}}</code></p>\n<hr>\n', verbose_name='encabezado'),
        ),
    ]
