# Generated by Django 3.0.4 on 2020-04-28 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0008_auto_20200428_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportconfiguration',
            name='body',
            field=models.TextField(default='\n<h1>Informe diario {{now.strftime(\'%Y-%m-%d\')}}</h1>\n\n{% for m in models %}\n<div id="model-{{m.model_name()}}">\n    <h2>{{ m.model_name() }}</h2>\n\n    <p><q>{{ m.model_resume() }}</q></p>\n\n    {% for plot in m.plots.plot_all() %}\n        {{ plot.to_html() }}\n    {% endfor %}\n    </div>\n{% endfor %}\n', verbose_name='Cuerpo'),
        ),
    ]
