#!/usr/bin/env python
# -*- coding: utf-8 -*-

# This file is part of Arcovid-19 Brooks.
# Copyright (c) 2020, Juan B Cabral, Vanessa Daza, Diego García Lambas,
#                     Marcelo Lares, Nadia Luczywo, Dante Paz, Rodrigo Quiroga,
#                     Bruno Sanchez, Federico Stasyszyn.
# License: BSD-3-Clause
#   Full Text: https://github.com/ivco19/brooks/blob/master/LICENSE


# =============================================================================
# DOCS
# =============================================================================

"""Command useful to regulary clean all the data generated by the DEMO site.

"""


# =============================================================================
# IMPORTS
# =============================================================================

import shutil
import os
import django.apps

from django.conf import settings

from django.core.management.base import BaseCommand, CommandError


# =============================================================================
# CLASS
# =============================================================================

class Command(BaseCommand):
    help = "Clean the database and remove all the uploaded files"

    def handle(self, *args, **options):
        if not settings.DEMO_MODE:
            raise CommandError("This command can only run in DEMO_MODE")

        print(f"!!! Reset DB")
        for model in django.apps.apps.get_models():
            model.objects.all().delete()

        print(f"!!! Removing {settings.MEDIA_ROOT}")
        if os.path.exists(settings.MEDIA_ROOT):
            shutil.rmtree(settings.MEDIA_ROOT)
